# Build
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
permalink: /blog/:year/:month/:title
timezone: America/New_York
url: http://pittcsc.org

# Content
defaults:
  - scope:
      path: ''
      type: jobs
    values:
      layout: job

collections:
  jobs:
    output: true
    permalink: /jobs/:path/

# Assets
sass:
  sass_dir: assets/css
